name: Pipeline de CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar o repositório
      uses: actions/checkout@v2
      
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependências
      run: |
        npm install 
        
    - name: Rodar testes
      run: |
        npm test  
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar o repositório
      uses: actions/checkout@v2
      
    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar ferramentas de lint
      run: |
        npm install -g eslint 
        
    - name: Rodar ESLint
      run: |
        eslint .  

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Baixar o repositório
      uses: actions/checkout@v2
      
    - name: Realizar o deploy
      run: |
      
