name: Atualização Diária

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_code:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o repositório
      uses: actions/checkout@v2 

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Instalar dependências
      run: |
        npm install  # Instala as dependências do projeto

    - name: Rodar testes
      run: |
        npm test  # Roda os testes definidos no projeto
